language: rust

stages:
- test
- name: deploy
  if: tag =~ /^\d+\.\d+\.\d+.*$/

env:
  global:
  - RUST_BACKTRACE=1

# See http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
before_script:
- export -f travis_nanoseconds
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

matrix:
  allow_failures:
  - env: NIGHTLY=1
  fast_finish: true
  include:
  #  _      _       _   
  # | |    (_)     | |  
  # | |     _ _ __ | |_ 
  # | |    | | '_ \| __|
  # | |____| | | | | |_ 
  # |______|_|_| |_|\__|
  - name: "stable lint"
    stage: test
    rust: stable
    os: linux
    script: .ci/lint.sh

  - name: "beta lint"
    stage: test
    rust: beta
    os: linux
    script: .ci/lint.sh

  #  _______        _   
  # |__   __|      | |  
  #    | | ___  ___| |_ 
  #    | |/ _ \/ __| __|
  #    | |  __/\__ \ |_ 
  #    |_|\___||___/\__|
  - name: "stable test linux"
    stage: test
    rust: stable
    os: linux
    script: .ci/test.sh

  - name: "beta test linux"
    stage: test
    rust: beta
    os: linux
    script: .ci/test.sh

  - name: "nightly test linux"
    stage: test
    rust: nightly
    script: .ci/test.sh
    env:
    - NIGHTLY=1

  - name: "stable test osx"
    rust: stable
    os: osx
    script: .ci/test.sh

  - name: "stable test windows"
    rust: stable
    os: windows
    script: .ci/test.sh

  #  _____       _     _ _     _     
  # |  __ \     | |   | (_)   | |    
  # | |__) |   _| |__ | |_ ___| |__  
  # |  ___/ | | | '_ \| | / __| '_ \ 
  # | |   | |_| | |_) | | \__ \ | | |
  # |_|    \__,_|_.__/|_|_|___/_| |_|
  - stage: deploy
    rust: stable
    os: linux
    script: echo "deploying $TRAVIS_TAG to crates.io"
    deploy:
      provider: cargo
      token:
        secure: hdeE47YTFWtH0AlPe0KJoUX/rhATsG2McNS5Vnl4cQDYqlvJkwWKnwuN5/f1CfcQcIWHhGbwJqur2gstLpwgHz9FL+SsbZra6PqdQJc+IsyEbSoFYeS7WEuz0t3WN9swHw3iEj6WYeNdAGYk/00/eyaVh7PG3Yc/t4ZPpJNntiVfAzEZFaRvaHFQqasA/DIFnmNGp4l4WYi29sFQ6ykCN+7oYsnowSnjRcA7MjrcuijNo5tUGX6K328awIZLW5ptix8PGFDLkQ/R5S/Bf56LfaunQP6HLnx4qtpXN4LxyrOxbzyjMxWySvvMHvZrR4cK4p+z6o4hqAzg0Gvx1mA29VGuIT5blbcndRHUC2gq4W2NpS5UH/PtZiKrkp+vCTmyQvbSGCNajpvNmJi7fs4+lRSCCFy11lJS+D0pgqEQzgFHr8L+7p2qYD0VRQ2+64k/FuMElTsjM9KUfKxg/oDaOoQoE3gqFYEYUPJUQdNfxStFYfJi7rKWFAJWR0CueZWp0+UX5NP0t+rkLNxtaqb1M5E8O2KpcYetem5eUZtT1jgmZvGK9V9PkpYysuoc50W7ewV5Cjzk5xR6JQUft4zzyPnE2PuJLU6huFfjZc2NZVgg6zp3LnX8aIBEIAqIbxB8RbhDeyfNtOUhpn8I7qLlAbq5VosGtHOzm8OJqvyg5Rg=
      on:
        repo: EmbarkStudios/tame-oauth
        tags: true
