[package]
name = "tame-oauth"
version = "0.2.1"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "A (very) simple oauth 2.0 library"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/tame-oauth"
homepage = "https://github.com/EmbarkStudios/tame-oauth"
repository = "https://github.com/EmbarkStudios/tame-oauth"
keywords = ["oauth", "tame", "sans-io", "gcp"]
readme = "README.md"

[badges]
travis-ci = { repository = "EmbarkStudios/tame-oauth", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
doctest = false
path = "src/lib.rs"

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
err-derive = "0.2.0"
lock_api = "0.3.1"
parking_lot = "0.9.0"
# ring is currently set to this verion until more parts of the ecosystem move
# to the newer 0.15+ version(s) as ring is a native dependency and can't have
# multiple versions
ring = { version = "0.14.6", optional = true }
serde = { version = "1.0.94", features = [ "derive" ] }
serde_json = "1.0.40"
twox-hash = { version = "1.4.2", default-features = false }
untrusted = { version = "0.6.2", optional = true }
url = { version = "1.7.2", optional = true }

[dev-dependencies]
reqwest = { version = "0.9.18", default-features = false, features = [ "rustls-tls" ] }

[features]
default = ["gcp"]
gcp = ["jwt", "url"]
jwt = ["ring", "untrusted"]
