[package]
name = "simple-oauth"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "A (very) tiny oauth 2.0 library"
license = "MIT/Apache-2.0"

[lib]
doctest = false

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
chrono = "0.4.7"
failure = "0.1.5"
http = "0.1.17"
#jsonwebtoken = { git = "https://github.com/Keats/jsonwebtoken.git", rev = "3c62b98", optional = true }
jsonwebtoken = { path = "vendor/jsonwebtoken", version = "7.0.0", optional = true }
lock_api = "0.2.0"
parking_lot = "0.8.0"
serde = { version = "1.0.94", features = [ "derive" ] }
serde_json = "1.0.40"
twox-hash = { version = "1.4.1", default-features = false }
url = { version = "1.7.2", optional = true }

[dev-dependencies]
reqwest = { version = "0.9.18", default-features = false, features = [ "rustls" ] }

[features]
default = ["gcp"]
gcp = ["jsonwebtoken", "url"]
